template = '''
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: docker
  name: docker
spec:
  containers:
  - command:
    - sleep
    - "3600"
    image: docker
    name: docker
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker
  volumes:
  - name: docker
    hostPath:
      path: /var/run/docker.sock
'''


podTemplate(cloud: 'kubernetes', label: 'docker', showRawYaml: false, yaml: template) {
node("docker"){
container("docker"){
stage("Git clone"){
git branch: 'main', url: 'https://github.com/kaizenacademy/jenkins-october-terraform.git'
}
withCredentials([usernamePassword(credentialsId: 'docker-creds', passwordVariable: 'DOCKER_PASS', usernameVariable: 'DOCKER_USER')]) {
stage("Docker Build"){

sh """
cd docker
docker build -t ${DOCKER_USER}/test:0.0.3 .
"""
}
stage("Docker Push"){
sh """
docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
docker push ${DOCKER_USER}/test:0.0.3
"""
build 'helm'
}
}


}
}
}

